# Configuration for ensemble_3models.py
# Default: batch_size=10, 1000 ảnh, numeric order

defaults:
  - _self_

data:
  batch_size: 10
  num_samples: 1000
  output: "./LAT"
  cle_data_path: "resources/images/bigscale_1000"
  tgt_data_path: "resources/images/target_images_1000"

optim:
  alpha: 1.0
  epsilon: 16
  steps: 300

model:
  input_res: 224
  use_source_crop: true
  use_target_crop: true
  crop_scale: [0.5, 0.9]
  ensemble: true
  device: "cuda:0"
  backbone: ["B16", "B32", "Laion"]

wandb:
  project: "local_adversarial_attack"
  entity: ??? # fill your wandb entity

blackbox:
  model_name: "gemini"  # Can be gpt4o, claude, gemini, gpt_4v
  batch_size: 1
  timeout: 30

attack: 'fgsm' # [fgsm, mifgsm, pgd]
